### ISSUE TITLE
RUN ERROR

### ISSUE THREAD

**Issue by pan111-pp** [nguyetn89/skeleton-HMM#1]
Traceback (most recent call last):
File "main.py", line 157, in
main(sys.argv)
File "main.py", line 153, in main
HMMgait3_fullsequence(data, np.where(separation == 'test')[0], n_subjects = data.shape[0], n_gaits = data.shape[1],
File "main.py", line 66, in HMMgait3_fullsequence
hmm_model = train_hmm(train_cycle_vectors, state_num, obs_num)
File "/root/pwc/skeleton-HMM-master/func_HMM.py", line 74, in train_hmm
model.fit(data_transposed, lengths=obs_lengths_array)
File "/root/anaconda3/envs/pwc_ske/lib/python3.8/site-packages/hmmlearn/base.py", line 468, in fit
self._init(X, lengths)
File "/root/anaconda3/envs/pwc_ske/lib/python3.8/site-packages/hmmlearn/hmm.py", line 895, in _init
super()._init(X, lengths=None)
File "/root/anaconda3/envs/pwc_ske/lib/python3.8/site-packages/hmmlearn/base.py", line 908, in _init
self._check_and_set_n_features(X)
File "/root/anaconda3/envs/pwc_ske/lib/python3.8/site-packages/hmmlearn/_emissions.py", line 317, in _check_and_set_n_features
super()._check_and_set_n_features(X)
File "/root/anaconda3/envs/pwc_ske/lib/python3.8/site-packages/hmmlearn/base.py", line 527, in _check_and_set_n_features
raise ValueError(
ValueError: Unexpected number of dimensions, got 1 but expected 43

What seems to be the problem with this?

**Comment by hajkeoadf** [comment]
same problem
